export const HOSTELS_FETCH = "HOSTELS_FETCH";
export const HOSTEL_FETCH="HOSTEL_FETCH";
export const HOSTEL_LOADING = "HOSTEL_LOADING";
export const LOAD_REVIEWS = "LOAD_REVIEWS";
export const ADD_REVIEW = "ADD_REVIEW";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const RESET_HOSTEL_LOADING = "RESET_HOSTEL_LOADING";